### PR TITLE
small README fixes and added color debug

### PR DESCRIPTION
**Pull request by fefer**
1. Changed both README.md from "mac" to "macsad" (because of new repo name)

2. Added colors using debug:

- Red: Errors/Problems
- Blue: Info
- Green: Broadcast
- Magenta: debug

### CODE REVIEW

**Comment by fefer** [comment]
1. If I got what you said, take a look and you'll find that I did not add printf at all, it was previously there. So, what is your suggestion to this?
2. My view is that the primitives problems (can't add_header, remove_header, etc as red) and Broadcast/Unicast (maybe as green) should all be highlighted, can't we make something about it?

**Comment by c3m3gyanesh** [comment]
1) I told you that we shouldn't have printf in the code. These primitives are added by you. So if there is a printf there, you need to remove them and make the code as our coding style. You are the owner of those code now.
2) any error condition should be in red (including can't add_header etc).  Broadcast/Unicast can be printed in other color. 
But all the color code will be added into the definition of "error" "info" etc. Not at the other part of the code when you try to print the message.

**Comment by fefer** [comment]
1. Ok

2. So, I can create an ERROR (can't add_header, etc) and ROUTE (broadcast , unicast, etc messages output) section at backend.h, right? Similar to what's done by DEBUG and INFO.

**Comment by c3m3gyanesh** [comment]
For now we used debug to print error messages, and info to print other details.
If you want to create another for Error, then please define properly the "error" "info" "debug" types. what each type will print?

For unicast/broadcast, we can continue using sigg, or we can rename it to "demo", as we use it only when doing a demo or to verify if the forwarding is working or not.

**Pull request closed without merging**
